import { describe, expect, it } from "vitest";
import {
  hasAgentReply,
  hasGatewayFallbackSignal,
  isGatewayServiceNotLoadedError,
  isPlaceholderGatewayToken,
  normalizeGatewayTokenValue,
  parseGatewayStatusRunning,
  summarizeAgentOutput
} from "../src/gateway.js";

describe("hasAgentReply", () => {
  it("returns true when payload contains text", () => {
    const stdout = JSON.stringify({
      payloads: [{ text: "ok" }]
    });

    expect(hasAgentReply(stdout)).toBe(true);
  });

  it("returns false when payloads is empty", () => {
    const stdout = JSON.stringify({ payloads: [] });
    expect(hasAgentReply(stdout)).toBe(false);
  });

  it("returns true when payload exists under result.payloads", () => {
    const stdout = JSON.stringify({
      runId: "2b76ef06-fa00-4b6a-802d-ae52907113b8",
      status: "ok",
      summary: "completed",
      result: {
        payloads: [{ text: "All systems operational." }]
      }
    });

    expect(hasAgentReply(stdout)).toBe(true);
  });

  it("returns false for invalid json", () => {
    expect(hasAgentReply("not-json")).toBe(false);
  });

  it("returns true when json is wrapped by warning text", () => {
    const wrapped = [
      "[warn] plugin mismatch",
      "{\"payloads\":[{\"text\":\"ok from gateway\"}]}",
      "[info] trailing line"
    ].join("\n");

    expect(hasAgentReply(wrapped)).toBe(true);
  });
});

describe("hasGatewayFallbackSignal", () => {
  it("returns true when output contains fallback marker", () => {
    expect(hasGatewayFallbackSignal("Gateway agent failed; falling back to embedded")).toBe(true);
  });

  it("returns false for normal output", () => {
    expect(hasGatewayFallbackSignal("{\"payloads\":[{\"text\":\"ok\"}]}")).toBe(false);
  });
});

describe("summarizeAgentOutput", () => {
  it("returns first non-empty lines joined as summary", () => {
    const output = "\nline-a\nline-b\nline-c\n";
    expect(summarizeAgentOutput(output, 2)).toBe("line-a | line-b");
  });

  it("returns fallback text for empty output", () => {
    expect(summarizeAgentOutput("   \n \n")).toBe("无命令输出");
  });
});

describe("isPlaceholderGatewayToken", () => {
  it("returns true for empty or placeholder tokens", () => {
    expect(isPlaceholderGatewayToken("")).toBe(true);
    expect(isPlaceholderGatewayToken("   ")).toBe(true);
    expect(isPlaceholderGatewayToken("CHANGE_ME_OPENCLAW_GATEWAY_TOKEN")).toBe(true);
    expect(isPlaceholderGatewayToken("CHANGE_ME_TOKEN")).toBe(true);
    expect(isPlaceholderGatewayToken("<auto-generated-token>")).toBe(true);
  });

  it("returns false for custom tokens", () => {
    expect(isPlaceholderGatewayToken("my-custom-token-123")).toBe(false);
  });
});

describe("normalizeGatewayTokenValue", () => {
  it("replaces empty/placeholder tokens", () => {
    const generated = "generated-token";
    expect(normalizeGatewayTokenValue("", () => generated)).toEqual({
      token: generated,
      replaced: true
    });
    expect(normalizeGatewayTokenValue("CHANGE_ME_OPENCLAW_GATEWAY_TOKEN", () => generated)).toEqual({
      token: generated,
      replaced: true
    });
  });

  it("keeps custom token", () => {
    expect(normalizeGatewayTokenValue("custom-123", () => "generated")).toEqual({
      token: "custom-123",
      replaced: false
    });
  });
});

describe("isGatewayServiceNotLoadedError", () => {
  it("detects service-not-loaded restart errors", () => {
    expect(isGatewayServiceNotLoadedError("Gateway service not loaded")).toBe(true);
    expect(isGatewayServiceNotLoadedError("service not loaded")).toBe(true);
  });

  it("returns false for unrelated errors", () => {
    expect(isGatewayServiceNotLoadedError("token mismatch")).toBe(false);
  });
});

describe("parseGatewayStatusRunning", () => {
  it("returns true when status output indicates running", () => {
    expect(parseGatewayStatusRunning("Runtime: running")).toBe(true);
    expect(parseGatewayStatusRunning("RPC probe: ok")).toBe(true);
    expect(parseGatewayStatusRunning("state=running")).toBe(true);
  });

  it("returns false when not running", () => {
    expect(parseGatewayStatusRunning("status=stopped")).toBe(false);
  });
});
