export class AppError extends Error {
  public readonly code: string;
  public readonly causeValue?: unknown;

  constructor(code: string, message: string, causeValue?: unknown) {
    super(message);
    this.name = "AppError";
    this.code = code;
    this.causeValue = causeValue;
  }
}

export const ErrorCodes = {
  API_BASE_MISSING: "API_BASE_MISSING",
  PLATFORM_NOT_SUPPORTED: "PLATFORM_NOT_SUPPORTED",
  LICENSE_INVALID: "LICENSE_INVALID",
  SESSION_INVALID: "SESSION_INVALID",
  INSTALL_FAILED: "INSTALL_FAILED",
  VERSION_NOT_FOUND: "VERSION_NOT_FOUND",
  PATH_FIX_FAILED: "PATH_FIX_FAILED",
  ONBOARD_FAILED: "ONBOARD_FAILED",
  CONFIG_SCHEMA_INVALID: "CONFIG_SCHEMA_INVALID",
  CONFIG_VALIDATION_FAILED: "CONFIG_VALIDATION_FAILED",
  CONFIG_WRITE_FAILED: "CONFIG_WRITE_FAILED",
  MODEL_TEST_FAILED: "MODEL_TEST_FAILED",
  GATEWAY_FAILED: "GATEWAY_FAILED",
  AGENT_CHECK_FAILED: "AGENT_CHECK_FAILED",
  CHANNEL_BIND_FAILED: "CHANNEL_BIND_FAILED",
  CHANNEL_PLUGIN_INSTALL_FAILED: "CHANNEL_PLUGIN_INSTALL_FAILED",
  TELEGRAM_BIND_FAILED: "TELEGRAM_BIND_FAILED",
  TELEGRAM_DISCOVERY_TIMEOUT: "TELEGRAM_DISCOVERY_TIMEOUT",
  TELEGRAM_WEAK_VALIDATION_FAILED: "TELEGRAM_WEAK_VALIDATION_FAILED",
  TELEGRAM_API_INVALID: "TELEGRAM_API_INVALID",
  NETWORK_FAILED: "NETWORK_FAILED",
  UNKNOWN: "UNKNOWN"
} as const;
